using System;
using System.Collections.Generic;

namespace GameTime.Models
{
    public class ItemList : Item
    {
        public List<Item> AllItems { get; set; }

        public ItemList()
        {
            AllItems = new List<Item>();
            AllItems.Add(new Weapon() { ID = 1, Name = "C96", Subname = "96", Rarity = Rarity.Common, Value = 1769.53m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B8MM, HighestDamage = 15, LowestDamage = 5, Cooldown = TimeSpan.FromMinutes(16.62), IsPurchaseable = true });
            AllItems.Add(new Weapon() { ID = 2, Name = "Bow", Rarity = Rarity.Common, Value = 1593.75m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.Arrow, HighestDamage = 12, LowestDamage = 5, Cooldown = TimeSpan.FromMinutes(14.9), IsPurchaseable = true });
            AllItems.Add(new Weapon() { ID = 3, Name = "Cruid Knife", Subname = "Cruid", Rarity = Rarity.Common, Value = 645.31m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 10, LowestDamage = 5, Cooldown = TimeSpan.FromMinutes(13.25), IsPurchaseable = true });
            AllItems.Add(new Ammo() { ID = 4, Name = "9mm", Subname = "9", Rarity = Rarity.Common, Value = 1036.71m, Type = Ammunition.B9mm, });
            AllItems.Add(new Weapon() { ID = 5, Name = "Glock", Rarity = Rarity.Common, Value = 2096.87m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B9mm, HighestDamage = 15, LowestDamage = 10, Cooldown = TimeSpan.FromMinutes(19.2), IsPurchaseable = true });
            AllItems.Add(new Weapon() { ID = 6, Name = "Stone", Rarity = Rarity.Common, Value = 112.5m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 1, LowestDamage = 0, Cooldown = TimeSpan.FromMinutes(1), IsPurchaseable = true });
            AllItems.Add(new Ammo() { ID = 7, Name = "8mm", Subname = "8", Rarity = Rarity.Common, Value = 778.90m, Type = Ammunition.B8MM, });
            AllItems.Add(new Weapon() { ID = 8, Name = "Wooden Spear", Subname = "Spear", Rarity = Rarity.Common, Value = 850.75m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 11, LowestDamage = 4, Cooldown = TimeSpan.FromMinutes(13.15), IsPurchaseable = true });
            AllItems.Add(new Armor() { ID = 9, Name = "Wooden Shield", Subname = "Wooden", Rarity = Rarity.Common, Value = 8662.5m, IsActive = false, ProtectionRate = 15, IsPurchaseable = true });
            AllItems.Add(new Weapon() { ID = 10, Name = "Dart", Rarity = Rarity.Common, Value = 120.25m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 1, Cooldown = TimeSpan.FromMinutes(1.5) });
            AllItems.Add(new Ammo() { ID = 11, Name = "Arrow", Rarity = Rarity.Common, Value = 944.28m, Type = Ammunition.Arrow, IsPurchaseable = true });
            AllItems.Add(new Weapon() { ID = 12, Name = "Pellet Gun", Subname = "PelletGun", Rarity = Rarity.Common, Value = 187.5m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.PlasticPellet, HighestDamage = 2, LowestDamage = 0, Cooldown = TimeSpan.FromMinutes(1.5) });
            AllItems.Add(new Armor() { ID = 13, Name = "Plastic Shield", Subname = "Plastic", Value = 5775.62m, IsActive = false, ProtectionRate = 10, Rarity = Rarity.Common, IsPurchaseable = true });
            AllItems.Add(new Healing() { ID = 14, Name = "Alcohol Wipe", Subname = "Alcohol", Rarity = Rarity.Common, Value = 205.34m, MaxHealingRate = 2, Cooldown = TimeSpan.FromMinutes(2.3), IsPurchaseable = true });
            AllItems.Add(new Weapon() { ID = 15, Name = "Bat", Rarity = Rarity.Common, Value = 323.43m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 3, Cooldown = TimeSpan.FromMinutes(6.25), IsPurchaseable = true });
            AllItems.Add(new Healing() { ID = 16, Name = "Bandaid", Rarity = Rarity.Common, Value = 157.5m, MaxHealingRate = 1, Cooldown = TimeSpan.FromMinutes(1.15), IsPurchaseable = true });
            AllItems.Add(new Weapon() { ID = 17, Name = "P08", Rarity = Rarity.Common, Value = 2121.09m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B9mm, HighestDamage = 14, LowestDamage = 10, Cooldown = TimeSpan.FromMinutes(18.35), IsPurchaseable = true });
            AllItems.Add(new Weapon() { ID = 18, Name = "Razor", Rarity = Rarity.Common, Value = 534.37m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 5, Cooldown = TimeSpan.FromMinutes(7.75), IsPurchaseable = true });
            AllItems.Add(new Money() { ID = 19, Name = "Wallet", Rarity = Rarity.Common, Value = 200, HighestAmount = 500m, LowestAmount = 100m, IsSellable = false });
            AllItems.Add(new Weapon() { ID = 20, Name = "Remington", Rarity = Rarity.Rare, Value = 12421.87m, WeaponType = WeaponType.Firearm, FireRate = 6, HighestDamage = 15, LowestDamage = 1, Ammo = Ammunition.B12Gauge, Cooldown = TimeSpan.FromMinutes(151.5) });
            AllItems.Add(new Weapon() { ID = 21, Name = "Stevens 555", Subname = "Stevens", Rarity = Rarity.Common, Value = 3304.68m, WeaponType = WeaponType.Firearm, FireRate = 12, HighestDamage = 3, LowestDamage = 0, Ammo = Ammunition.B12Gauge, Cooldown = TimeSpan.FromMinutes(56.03), IsPurchaseable = true });
            AllItems.Add(new Ammo() { ID = 22, Name = "12 Gauge", Subname = "12", Rarity = Rarity.Common, Value = 1036.71m, Type = Ammunition.B12Gauge });
            AllItems.Add(new Weapon() { ID = 23, Name = "Paint Gun", Subname = "PaintGun", Rarity = Rarity.Common, Value = 275.39m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.Paintball, HighestDamage = 2, LowestDamage = 0, Cooldown = TimeSpan.FromMinutes(1.73) });
            AllItems.Add(new Weapon() { ID = 24, Name = "Sawed-off", Subname = "Sawedoff", Rarity = Rarity.Common, Value = 2250m, WeaponType = WeaponType.Firearm, FireRate = 12, HighestDamage = 2, LowestDamage = 0, Ammo = Ammunition.B12Gauge, Cooldown = TimeSpan.FromMinutes(43.37), IsPurchaseable = true });
            AllItems.Add(new Ammo() { ID = 25, Name = "Paintball", Subname = "Paint", Rarity = Rarity.Common, Value = 231.84m, Type = Ammunition.Paintball });
            AllItems.Add(new Ammo() { ID = 26, Name = "Plastic Pellet", Subname = "Pellet", Rarity = Rarity.Common, Value = 196.44m, Type = Ammunition.PlasticPellet });
            AllItems.Add(new Weapon() { ID = 27, Name = "Pool Cue", Subname = "Pool", Rarity = Rarity.Common, Value = 323.43m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 3, Cooldown = TimeSpan.FromMinutes(6.25), IsPurchaseable = true });
            AllItems.Add(new Attachment() { ID = 28, Name = "Mag Grip", Subname = "Grip", Rarity = Rarity.Common, Value = 937.44m, IsActive = false, Ability = Addon.ReduceCooldown, Intensity = 2 });
            AllItems.Add(new Attachment() { ID = 29, Name = "Vertical Grip", Subname = "Vertical", Rarity = Rarity.Common, Value = 1072.85m, IsActive = false, Ability = Addon.HighestDamageIncrease, Intensity = 1 });
            AllItems.Add(new Weapon() { ID = 34, Name = "Staff", Rarity = Rarity.Common, Value = 428.9m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 4, Cooldown = TimeSpan.FromMinutes(7), IsPurchaseable = true });
            AllItems.Add(new Weapon() { ID = 50, Name = "Firecracker", Subname = "Fire", Rarity = Rarity.Common, Value = 300.24m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 5, LowestDamage = 0, Cooldown = TimeSpan.FromMinutes(9.5), IsPurchaseable = true });
            AllItems.Add(new Weapon() { ID = 51, Name = "P90", Subname = "90", Rarity = Rarity.Uncommon, Value = 4687.5m, WeaponType = WeaponType.Firearm, FireRate = 2, Ammo = Ammunition.B9mm, HighestDamage = 12, LowestDamage = 5, Cooldown = TimeSpan.FromMinutes(43.18), IsPurchaseable = true });
            AllItems.Add(new Weapon() { ID = 52, Name = "Tomahawk", Subname = "Toma", Rarity = Rarity.Uncommon, Value = 1836.96m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 15, Cooldown = TimeSpan.FromMinutes(32.75), IsPurchaseable = true });
            AllItems.Add(new Ammo() { ID = 53, Name = "5.56mm", Subname = "556", Rarity = Rarity.Uncommon, Value = 4038.28m, Type = Ammunition.B556mm, });
            AllItems.Add(new Healing() { ID = 54, Name = "First Aid", Subname = "Aid", Rarity = Rarity.Uncommon, Value = 3864.22m, MaxHealingRate = 35, LowestHealingRate = 25, Cooldown = TimeSpan.FromMinutes(34.5), IsPurchaseable = true });
            AllItems.Add(new Weapon() { ID = 55, Name = "P1911", Subname = "19", Rarity = Rarity.Uncommon, Value = 4869.53m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B45APC, HighestDamage = 18, Cooldown = TimeSpan.FromMinutes(42.155), IsPurchaseable = true });
            AllItems.Add(new Weapon() { ID = 56, Name = "Thompson", Subname = "Tom", Rarity = Rarity.Uncommon, Value = 5965.62m, WeaponType = WeaponType.Firearm, FireRate = 2, Ammo = Ammunition.B45APC, HighestDamage = 17, LowestDamage = 5, Cooldown = TimeSpan.FromMinutes(53.95), IsPurchaseable = true });
            AllItems.Add(new Attachment() { ID = 57, Name = "Laser Sight", Subname = "Laser", Rarity = Rarity.Uncommon, Value = 4672.32m, IsActive = false, Ability = Addon.HighestDamageIncrease, Intensity = 5 });
            AllItems.Add(new Armor() { ID = 58, Name = "Tactical Vest", Subname = "Tactical", Rarity = Rarity.Uncommon, Value = 13075.83m, IsActive = false, ProtectionRate = 40 });
            AllItems.Add(new Ammo() { ID = 59, Name = ".30 Carbine", Subname = ".30", Rarity = Rarity.Uncommon, Value = 3695.31m, Type = Ammunition.B30Carbine });
            AllItems.Add(new Weapon() { ID = 60, Name = "Five-Seven", Subname = "FiveSeven", Rarity = Rarity.Uncommon, Value = 5139.06m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B57, HighestDamage = 20, LowestDamage = 15, Cooldown = TimeSpan.FromMinutes(40.257), IsPurchaseable = true });
            AllItems.Add(new Ammo() { ID = 61, Name = "5.7mm", Subname = "57", Rarity = Rarity.Uncommon, Value = 2347.65m, Type = Ammunition.B57, });
            AllItems.Add(new Weapon() { ID = 62, Name = "Javelin", Subname = "Jave", Rarity = Rarity.Uncommon, Value = 1713.12m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 15, LowestDamage = 10, Cooldown = TimeSpan.FromMinutes(33.55), IsPurchaseable = true });
            AllItems.Add(new Healing() { ID = 63, Name = "Bandage", Subname = "Bandage", Rarity = Rarity.Uncommon, Value = 1832m, MaxHealingRate = 20, LowestHealingRate = 10, Cooldown = TimeSpan.FromMinutes(17.25), IsPurchaseable = true });
            AllItems.Add(new Attachment() { ID = 64, Name = "Mag Strap", Subname = "Strap", Rarity = Rarity.Uncommon, Value = 2251.79m, IsActive = false, Ability = Addon.ReduceCooldown, Intensity = 10 });
            AllItems.Add(new Attachment() { ID = 65, Name = "Weapon Stand", Subname = "Stand", Rarity = Rarity.Uncommon, Value = 2646.87m, IsActive = false, Ability = Addon.HighestDamageIncrease, Intensity = 3 });
            AllItems.Add(new Money() { ID = 66, Name = "Lock Box", Subname = "Box", Rarity = Rarity.Uncommon, Value = 1000m, HighestAmount = 1500m, LowestAmount = 500, IsSellable = false });
            AllItems.Add(new Weapon() { ID = 67, Name = "PPSH", Subname = "PPSH", Rarity = Rarity.Uncommon, Value = 7565.62m, WeaponType = WeaponType.Firearm, FireRate = 3, Ammo = Ammunition.B762mm, HighestDamage = 20, LowestDamage = 5, Cooldown = TimeSpan.FromMinutes(109.387), IsPurchaseable = true });
            AllItems.Add(new Weapon() { ID = 68, Name = "Cross Bow", Subname = "CrossBow", Rarity = Rarity.Uncommon, Value = 4330.46m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.Arrow, HighestDamage = 16, Cooldown = TimeSpan.FromMinutes(38.36), IsPurchaseable = true });
            AllItems.Add(new Armor() { ID = 69, Name = "Mail Armor", Subname = "Mail", Rarity = Rarity.Uncommon, Value = 11037.52m, IsActive = false, ProtectionRate = 20 });
            AllItems.Add(new Weapon() { ID = 70, Name = "Broadsword", Subname = "Sword", Rarity = Rarity.Uncommon, Value = 1836.56m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 15, Cooldown = TimeSpan.FromMinutes(32.75), IsPurchaseable = true });
            AllItems.Add(new Weapon() { ID = 71, Name = "G36C", Subname = "G36", Rarity = Rarity.Uncommon, Value = 4156.87m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B556mm, HighestDamage = 40, LowestDamage = 10, Cooldown = TimeSpan.FromMinutes(64.925) });
            AllItems.Add(new Weapon() { ID = 72, Name = "MK 12", Subname = "MK", Rarity = Rarity.Uncommon, Value = 6103.9m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B556mm, HighestDamage = 30, Cooldown = TimeSpan.FromMinutes(89.592) });
            AllItems.Add(new Money() { ID = 73, Name = "Stash", Subname = "Stash", Rarity = Rarity.Uncommon, Value = 3000m, HighestAmount = 5000m, LowestAmount = 1000m, IsSellable = false });
            AllItems.Add(new Weapon() { ID = 74, Name = "Musket", Subname = "Musk", Rarity = Rarity.Uncommon, Value = 4803.9m, WeaponType = WeaponType.Firearm, HighestDamage = 60, LowestDamage = 1, FireRate = 1, Ammo = Ammunition.BallRound, Cooldown = TimeSpan.FromMinutes(121.85) });
            AllItems.Add(new Ammo() { ID = 75, Name = "Ball Round", Subname = "Ball", Rarity = Rarity.Uncommon, Value = 3614.95m, Type = Ammunition.BallRound });
            AllItems.Add(new Weapon() { ID = 76, Name = "AK-47", Subname = "AK", Rarity = Rarity.Rare, Value = 16428.12m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B762mm, HighestDamage = 65, LowestDamage = 35, Cooldown = TimeSpan.FromMinutes(125.031) });
            AllItems.Add(new Weapon() { ID = 77, Name = "M16A4", Subname = "M16", Rarity = Rarity.Rare, Value = 8850m, WeaponType = WeaponType.Firearm, FireRate = 3, Ammo = Ammunition.B556mm, HighestDamage = 14, LowestDamage = 7, Cooldown = TimeSpan.FromMinutes(95.156) });
            AllItems.Add(new Healing() { ID = 78, Name = "Blood Bag", Subname = "Blood", Rarity = Rarity.Epic, Value = 14784m, MaxHealingRate = 90, LowestHealingRate = 70, Cooldown = TimeSpan.FromMinutes(92) });
            AllItems.Add(new Armor() { ID = 79, Name = "Kevlar Set", Subname = "Kevlar", Rarity = Rarity.Rare, Value = 27562.5m, IsActive = false, ProtectionRate = 75 });
            AllItems.Add(new Weapon() { ID = 80, Name = "Combat Knife", Subname = "Combat", Rarity = Rarity.Rare, Value = 5510m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 35, LowestDamage = 30, Cooldown = TimeSpan.FromMinutes(73.875), IsPurchaseable = true });
            AllItems.Add(new Ammo() { ID = 81, Name = "7.62mm", Subname = "762", Rarity = Rarity.Rare, Value = 8921.87m, Type = Ammunition.B762mm });
            AllItems.Add(new Weapon() { ID = 82, Name = "M1 Garand", Subname = "Garand", Rarity = Rarity.Rare, Value = 15771.87m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B3006, HighestDamage = 50, LowestDamage = 40, Cooldown = TimeSpan.FromMinutes(120.031) });
            AllItems.Add(new Weapon() { ID = 83, Name = "Kar-98", Subname = "Kar", Rarity = Rarity.Rare, Value = 18068.75m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B762mm, HighestDamage = 55, Cooldown = TimeSpan.FromMinutes(186.593) });
            AllItems.Add(new Weapon() { ID = 84, Name = "MG-42", Subname = "MG42", Rarity = Rarity.Rare, Value = 17237.5m, WeaponType = WeaponType.Firearm, FireRate = 8, Ammo = Ammunition.B792, HighestDamage = 8, LowestDamage = 4, Cooldown = TimeSpan.FromMinutes(167.5) });
            AllItems.Add(new Healing() { ID = 85, Name = "Morphine", Subname = "Morph", Rarity = Rarity.Rare, Value = 8024.21m, MaxHealingRate = 65, LowestHealingRate = 50, Cooldown = TimeSpan.FromMinutes(69) });
            AllItems.Add(new Attachment() { ID = 86, Name = "Dual Mags", Subname = "Dual", Rarity = Rarity.Rare, Value = 6739.10m, IsActive = false, Ability = Addon.ReduceCooldown, Intensity = 25 });
            AllItems.Add(new Weapon() { ID = 87, Name = "Howa 89", Subname = "Howa", Rarity = Rarity.Rare, Value = 18134.37m, WeaponType = WeaponType.Firearm, FireRate = 4, Ammo = Ammunition.B556mm, HighestDamage = 16, LowestDamage = 8, Cooldown = TimeSpan.FromMinutes(94.25) });
            AllItems.Add(new Attachment() { ID = 88, Name = "4x Scope", Subname = "4x", Rarity = Rarity.Rare, Value = 9471.99m, IsActive = false, Ability = Addon.HighestDamageIncrease, Intensity = 10 });
            AllItems.Add(new Weapon() { ID = 89, Name = "Bayonet", Subname = "Bay", Rarity = Rarity.Rare, Value = 4825.62m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 30, LowestDamage = 25, Cooldown = TimeSpan.FromMinutes(60.5) });
            AllItems.Add(new Weapon() { ID = 90, Name = "M1 Carbine", Subname = "Carbine", Rarity = Rarity.Rare, Value = 11506.25m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B30Carbine, HighestDamage = 40, LowestDamage = 30, Cooldown = TimeSpan.FromMinutes(83.468) });
            AllItems.Add(new Ammo() { ID = 104, Name = "B56mm", Subname = "56", Rarity = Rarity.Rare, Value = 9640.62m, Type = Ammunition.B56mm });
            AllItems.Add(new Weapon() { ID = 91, Name = "M249", Subname = "249", Rarity = Rarity.Epic, Value = 38800.78m, WeaponType = WeaponType.Firearm, FireRate = 5, Ammo = Ammunition.B556mm, HighestDamage = 20, LowestDamage = 15, Cooldown = TimeSpan.FromMinutes(298.75) });
            AllItems.Add(new Weapon() { ID = 92, Name = "TAC-50", Subname = "Tac", Rarity = Rarity.Epic, Value = 44830.46m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B50BMG, HighestDamage = 90, Cooldown = TimeSpan.FromMinutes(240.875) });
            AllItems.Add(new Armor() { ID = 93, Name = "Ballistic Shield", Subname = "Ballistic", Rarity = Rarity.Epic, Value = 83312.5m, IsActive = false, ProtectionRate = 100 });
            AllItems.Add(new Ammo() { ID = 94, Name = ".50 BMG", Subname = "BMG", Rarity = Rarity.Epic, Value = 12582.19m, Type = Ammunition.B50BMG });
            AllItems.Add(new Weapon() { ID = 95, Name = "SG 550", Subname = "SG", Rarity = Rarity.Epic, Value = 24389.06m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B56mm, HighestDamage = 70, LowestDamage = 55, Cooldown = TimeSpan.FromMinutes(171.025) });
            AllItems.Add(new Ammo() { ID = 103, Name = "7.92mm", Subname = "792", Rarity = Rarity.Rare, Value = 7933.59m, Type = Ammunition.B792 });
            AllItems.Add(new Weapon() { ID = 96, Name = "Boys AT Rifle", Subname = "ATRifle", Rarity = Rarity.Unique, Value = 75634.98m, WeaponType = WeaponType.HeavyFirearm, FireRate = 1, Ammo = Ammunition.BRG55, HighestDamage = 25, Cooldown = TimeSpan.FromMinutes(83.468), Special = Special.ArmorBust });
            AllItems.Add(new Attachment() { ID = 97, Name = "Extended Clip", Subname = "Extended", Rarity = Rarity.Unique, Value = 50347.87m, Ability = Addon.IncreaseHitRate, Intensity = 1, IsActive = false });
            AllItems.Add(new Ammo() { ID = 98, Name = "RG.55", Subname = "rg", Rarity = Rarity.Unique, Type = Ammunition.BRG55, Value = 32812.5m });
            AllItems.Add(new Weapon() { ID = 99, Name = "Gattling Gun", Subname = "Gattling", Rarity = Rarity.Unique, Value = 133185.93m, WeaponType = WeaponType.Firearm, FireRate = 3, Ammo = Ammunition.GattlingDrum, HighestDamage = 40, LowestDamage = 20, Cooldown = TimeSpan.FromMinutes(887.062), Special = Special.SpreadShot });
            AllItems.Add(new Ammo() { ID = 100, Name = "GattlingDrum", Subname = "Drum", Rarity = Rarity.Unique, Value = 65625m, Type = Ammunition.GattlingDrum });
            AllItems.Add(new Utility() { ID = 101, Name = "Flare", Rarity = Rarity.Unique, Value = 35743.88m, Uses = 1, Special = Special.SupplyCall });
            AllItems.Add(new Utility() { ID = 102, Name = "Radar", Rarity = Rarity.Unique, Value = 69347.12m, Uses = 3, Special = Special.Scan });
            AllItems.Add(new Ammo() { ID = 105, Name = "30.06 Springfield", Subname = "30.06", Rarity = Rarity.Uncommon, Value = 4739.57m, Type = Ammunition.B3006 });
            AllItems.Add(new Crate() { ID = 106, Name = "Common Crate", Subname = "Common", Rarity = Rarity.Common, Value = 3368.53m, IsPurchaseable = true, IsSellable = false });
            AllItems.Add(new Crate() { ID = 107, Name = "Uncommon Crate", Subname = "Uncommon", Rarity = Rarity.Uncommon, Value = 6435.59m, IsPurchaseable = true, IsSellable = false });
            AllItems.Add(new Crate() { ID = 108, Name = "Rare Crate", Subname = "Rare", Rarity = Rarity.Rare, Value = 12437.58m, IsPurchaseable = true, IsSellable = false });
            AllItems.Add(new Crate() { ID = 109, Name = "Epic Crate", Subname = "Epic", Rarity = Rarity.Epic, Value = 35812.73m, IsSellable = false });
            AllItems.Add(new Crate() { ID = 110, Name = "Unique Crate", Subname = "Unique", Rarity = Rarity.Unique, Value = 107438.20m, IsSellable = false });
            AllItems.Add(new Money() { ID = 111, Name = "Money Bag", Subname = "Bag", Rarity = Rarity.Rare, Value = 6250m, HighestAmount = 10000m, LowestAmount = 2500m, IsSellable = false });
            AllItems.Add(new Money() { ID = 112, Name = "Vault", Subname = "Vlt", Rarity = Rarity.Epic, Value = 37500m, HighestAmount = 50000m, LowestAmount = 25000m, IsSellable = false });
        }
        public Item GetItem(Item item)
        {
            var itemID = item.ID;
            return itemID switch
            {
                1 => new Weapon() { ID = 1, Name = "C96", Subname = "96", Rarity = Rarity.Common, Value = 1769.53m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B8MM, HighestDamage = 15, LowestDamage = 5, Cooldown = TimeSpan.FromMinutes(16.62), IsPurchaseable = true },
                2 => new Weapon() { ID = 2, Name = "Bow", Rarity = Rarity.Common, Value = 1593.75m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.Arrow, HighestDamage = 12, LowestDamage = 5, Cooldown = TimeSpan.FromMinutes(14.9), IsPurchaseable = true },
                3 => new Weapon() { ID = 3, Name = "Cruid Knife", Subname = "Cruid", Rarity = Rarity.Common, Value = 645.31m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 10, LowestDamage = 5, Cooldown = TimeSpan.FromMinutes(13.25), IsPurchaseable = true },
                4 => new Ammo() { ID = 4, Name = "9mm", Subname = "9", Rarity = Rarity.Common, Value = 1036.71m, Type = Ammunition.B9mm, },
                5 => new Weapon() { ID = 5, Name = "Glock", Rarity = Rarity.Common, Value = 2096.87m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B9mm, HighestDamage = 15, LowestDamage = 10, Cooldown = TimeSpan.FromMinutes(19.2), IsPurchaseable = true },
                6 => new Weapon() { ID = 6, Name = "Stone", Rarity = Rarity.Common, Value = 112.5m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 1, LowestDamage = 0, Cooldown = TimeSpan.FromMinutes(1), IsPurchaseable = true },
                7 => new Ammo() { ID = 7, Name = "8mm", Subname = "8", Rarity = Rarity.Common, Value = 778.90m, Type = Ammunition.B8MM, },
                8 => new Weapon() { ID = 8, Name = "Wooden Spear", Subname = "Spear", Rarity = Rarity.Common, Value = 850.75m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 11, LowestDamage = 4, Cooldown = TimeSpan.FromMinutes(13.15), IsPurchaseable = true },
                9 => new Armor() { ID = 9, Name = "Wooden Shield", Subname = "Wooden", Rarity = Rarity.Common, Value = 8662.5m, IsActive = false, ProtectionRate = 15, IsPurchaseable = true },
                10 => new Weapon() { ID = 10, Name = "Dart", Rarity = Rarity.Common, Value = 120.25m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 1, Cooldown = TimeSpan.FromMinutes(1.5) },
                11 => new Ammo() { ID = 11, Name = "Arrow", Rarity = Rarity.Common, Value = 944.28m, Type = Ammunition.Arrow, IsPurchaseable = true },
                12 => new Weapon() { ID = 12, Name = "Pellet Gun", Subname = "PelletGun", Rarity = Rarity.Common, Value = 187.5m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.PlasticPellet, HighestDamage = 2, LowestDamage = 0, Cooldown = TimeSpan.FromMinutes(5), IsPurchaseable = true },
                13 => new Armor() { ID = 13, Name = "Plastic Shield", Subname = "Plastic", Value = 5775.62m, IsActive = false, ProtectionRate = 10, Rarity = Rarity.Common, IsPurchaseable = true },
                14 => new Healing() { ID = 14, Name = "Alcohol Wipe", Subname = "Alcohol", Rarity = Rarity.Common, Value = 205.34m, MaxHealingRate = 2, Cooldown = TimeSpan.FromMinutes(2.3), IsPurchaseable = true },
                15 => new Weapon() { ID = 15, Name = "Bat", Rarity = Rarity.Common, Value = 323.43m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 3, Cooldown = TimeSpan.FromMinutes(6.25), IsPurchaseable = true },
                16 => new Healing() { ID = 16, Name = "Bandaid", Rarity = Rarity.Common, Value = 157.5m, MaxHealingRate = 1, Cooldown = TimeSpan.FromMinutes(1.15), IsPurchaseable = true },
                17 => new Weapon() { ID = 17, Name = "P08", Rarity = Rarity.Common, Value = 2121.09m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B9mm, HighestDamage = 14, LowestDamage = 10, Cooldown = TimeSpan.FromMinutes(18.35), IsPurchaseable = true },
                18 => new Weapon() { ID = 18, Name = "Razor", Rarity = Rarity.Common, Value = 534.37m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 5, Cooldown = TimeSpan.FromMinutes(7.75), IsPurchaseable = true },
                19 => new Money() { ID = 19, Name = "Wallet", Rarity = Rarity.Common, Value = 200, HighestAmount = 500m, LowestAmount = 100m, IsSellable = false },
                20 => new Weapon() { ID = 20, Name = "Remington", Rarity = Rarity.Rare, Value = 12421.87m, WeaponType = WeaponType.Firearm, FireRate = 6, HighestDamage = 15, LowestDamage = 1, Ammo = Ammunition.B12Gauge, Cooldown = TimeSpan.FromMinutes(151.5) },
                21 => new Weapon() { ID = 21, Name = "Stevens 555", Subname = "Stevens", Rarity = Rarity.Common, Value = 3304.68m, WeaponType = WeaponType.Firearm, FireRate = 12, HighestDamage = 3, LowestDamage = 0, Ammo = Ammunition.B12Gauge, Cooldown = TimeSpan.FromMinutes(56.03), IsPurchaseable = true },
                22 => new Ammo() { ID = 22, Name = "12 Gauge", Subname = "12", Rarity = Rarity.Common, Value = 1036.71m, Type = Ammunition.B12Gauge, },
                23 => new Weapon() { ID = 23, Name = "Paint Gun", Subname = "PaintGun", Rarity = Rarity.Common, Value = 275.39m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.Paintball, HighestDamage = 2, LowestDamage = 0, Cooldown = TimeSpan.FromMinutes(1.73) },
                24 => new Weapon() { ID = 24, Name = "Sawed-off", Subname = "Sawedoff", Rarity = Rarity.Common, Value = 2250m, WeaponType = WeaponType.Firearm, FireRate = 12, HighestDamage = 2, LowestDamage = 0, Ammo = Ammunition.B12Gauge, Cooldown = TimeSpan.FromMinutes(43.37), IsPurchaseable = true },
                25 => new Ammo() { ID = 25, Name = "Paintball", Subname = "Paint", Rarity = Rarity.Common, Value = 231.84m, Type = Ammunition.Paintball },
                26 => new Ammo() { ID = 26, Name = "Plastic Pellet", Subname = "Pellet", Rarity = Rarity.Common, Value = 196.44m, Type = Ammunition.PlasticPellet },
                27 => new Weapon() { ID = 27, Name = "Pool Cue", Subname = "Pool", Rarity = Rarity.Common, Value = 323.43m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 3, Cooldown = TimeSpan.FromMinutes(6.25), IsPurchaseable = true },
                28 => new Attachment() { ID = 28, Name = "Mag Grip", Subname = "Grip", Rarity = Rarity.Common, Value = 937.44m, IsActive = false, Ability = Addon.ReduceCooldown, Intensity = 2 },
                29 => new Attachment() { ID = 29, Name = "Vertical Grip", Subname = "Vertical", Rarity = Rarity.Common, Value = 1072.85m, IsActive = false, Ability = Addon.HighestDamageIncrease, Intensity = 1 },
                34 => new Weapon() { ID = 34, Name = "Staff", Rarity = Rarity.Common, Value = 428.9m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 4, Cooldown = TimeSpan.FromMinutes(7), IsPurchaseable = true },
                50 => new Weapon() { ID = 50, Name = "Firecracker", Subname = "Fire", Rarity = Rarity.Common, Value = 300.24m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 5, LowestDamage = 0, Cooldown = TimeSpan.FromMinutes(9.5), IsPurchaseable = true },
                51 => new Weapon() { ID = 51, Name = "P90", Subname = "90", Rarity = Rarity.Uncommon, Value = 4687.5m, WeaponType = WeaponType.Firearm, FireRate = 2, Ammo = Ammunition.B9mm, HighestDamage = 12, LowestDamage = 5, Cooldown = TimeSpan.FromMinutes(43.18), IsPurchaseable = true },
                52 => new Weapon() { ID = 52, Name = "Tomahawk", Subname = "Toma", Rarity = Rarity.Uncommon, Value = 1836.96m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 15, Cooldown = TimeSpan.FromMinutes(32.75), IsPurchaseable = true },
                53 => new Ammo() { ID = 53, Name = "5.56mm", Subname = "556", Rarity = Rarity.Uncommon, Value = 4038.28m, Type = Ammunition.B556mm, },
                54 => new Healing() { ID = 54, Name = "First Aid", Subname = "Aid", Rarity = Rarity.Uncommon, Value = 3864.22m, MaxHealingRate = 35, LowestHealingRate = 25, Cooldown = TimeSpan.FromMinutes(34.5), IsPurchaseable = true },
                55 => new Weapon() { ID = 55, Name = "P1911", Subname = "19", Rarity = Rarity.Uncommon, Value = 4869.53m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B45APC, HighestDamage = 18, Cooldown = TimeSpan.FromMinutes(23.525), IsPurchaseable = true },
                56 => new Weapon() { ID = 56, Name = "Thompson", Subname = "Tom", Rarity = Rarity.Uncommon, Value = 5965.62m, WeaponType = WeaponType.Firearm, FireRate = 2, Ammo = Ammunition.B45APC, HighestDamage = 17, LowestDamage = 5, Cooldown = TimeSpan.FromMinutes(53.95), IsPurchaseable = true },
                57 => new Attachment() { ID = 57, Name = "Laser Sight", Subname = "Laser", Rarity = Rarity.Uncommon, Value = 4672.32m, IsActive = false, Ability = Addon.HighestDamageIncrease, Intensity = 5 },
                58 => new Armor() { ID = 58, Name = "Tactical Vest", Subname = "Tactical", Rarity = Rarity.Uncommon, Value = 13075.83m, IsActive = false, ProtectionRate = 40 },
                59 => new Ammo() { ID = 59, Name = ".30 Carbine", Subname = ".30", Rarity = Rarity.Uncommon, Value = 3695.31m, Type = Ammunition.B30Carbine },
                60 => new Weapon() { ID = 60, Name = "Five-Seven", Subname = "FiveSeven", Rarity = Rarity.Uncommon, Value = 5139.06m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B57, HighestDamage = 20, LowestDamage = 15, Cooldown = TimeSpan.FromMinutes(40.257), IsPurchaseable = true },
                61 => new Ammo() { ID = 61, Name = "5.7mm", Subname = "57", Rarity = Rarity.Uncommon, Value = 2347.65m, Type = Ammunition.B57, },
                62 => new Weapon() { ID = 62, Name = "Javelin", Subname = "Jave", Rarity = Rarity.Uncommon, Value = 1713.12m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 15, LowestDamage = 10, Cooldown = TimeSpan.FromMinutes(33.55), IsPurchaseable = true },
                63 => new Healing() { ID = 63, Name = "Bandage", Subname = "Bandage", Rarity = Rarity.Uncommon, Value = 1832m, MaxHealingRate = 20, LowestHealingRate = 10, Cooldown = TimeSpan.FromMinutes(17.25), IsPurchaseable = true },
                64 => new Attachment() { ID = 64, Name = "Mag Strap", Subname = "Strap", Rarity = Rarity.Uncommon, Value = 2251.79m, IsActive = false, Ability = Addon.ReduceCooldown, Intensity = 10 },
                65 => new Attachment() { ID = 65, Name = "Weapon Stand", Subname = "Stand", Rarity = Rarity.Uncommon, Value = 2646.87m, IsActive = false, Ability = Addon.HighestDamageIncrease, Intensity = 3 },
                66 => new Money() { ID = 66, Name = "Lock Box", Subname = "Box", Rarity = Rarity.Uncommon, Value = 1000m, HighestAmount = 1500m, LowestAmount = 500, IsSellable = false },
                67 => new Weapon() { ID = 67, Name = "PPSH", Subname = "PPSH", Rarity = Rarity.Uncommon, Value = 7565.62m, WeaponType = WeaponType.Firearm, FireRate = 3, Ammo = Ammunition.B762mm, HighestDamage = 20, LowestDamage = 5, Cooldown = TimeSpan.FromMinutes(109.387), IsPurchaseable = true },
                68 => new Weapon() { ID = 68, Name = "Cross Bow", Subname = "CrossBow", Rarity = Rarity.Uncommon, Value = 4330.46m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.Arrow, HighestDamage = 16, Cooldown = TimeSpan.FromMinutes(38.36), IsPurchaseable = true },
                69 => new Armor() { ID = 69, Name = "Mail Armor", Subname = "Mail", Rarity = Rarity.Uncommon, Value = 11037.52m, IsActive = false, ProtectionRate = 20 },
                70 => new Weapon() { ID = 70, Name = "Broadsword", Subname = "Sword", Rarity = Rarity.Uncommon, Value = 1836.56m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 15, Cooldown = TimeSpan.FromMinutes(32.75), IsPurchaseable = true },
                71 => new Weapon() { ID = 71, Name = "G36C", Subname = "G36", Rarity = Rarity.Uncommon, Value = 4156.87m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B556mm, HighestDamage = 40, LowestDamage = 10, Cooldown = TimeSpan.FromMinutes(64.925) },
                72 => new Weapon() { ID = 72, Name = "MK 12", Subname = "MK", Rarity = Rarity.Uncommon, Value = 6103.9m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B556mm, HighestDamage = 30, Cooldown = TimeSpan.FromMinutes(89.592) },
                73 => new Money() { ID = 73, Name = "Stash", Subname = "Stash", Rarity = Rarity.Uncommon, Value = 3000m, HighestAmount = 5000m, LowestAmount = 1000m, IsSellable = false },
                74 => new Weapon() { ID = 74, Name = "Musket", Subname = "Musk", Rarity = Rarity.Uncommon, Value = 4803.9m, WeaponType = WeaponType.Firearm, HighestDamage = 60, LowestDamage = 1, FireRate = 1, Ammo = Ammunition.BallRound, Cooldown = TimeSpan.FromMinutes(121.85) },
                75 => new Ammo() { ID = 75, Name = "Ball Round", Subname = "Ball", Rarity = Rarity.Uncommon, Value = 3614.95m, Type = Ammunition.BallRound },
                76 => new Weapon() { ID = 76, Name = "AK-47", Subname = "AK", Rarity = Rarity.Rare, Value = 16428.12m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B762mm, HighestDamage = 65, LowestDamage = 35, Cooldown = TimeSpan.FromMinutes(125.031) },
                77 => new Weapon() { ID = 77, Name = "M16A4", Subname = "M16", Rarity = Rarity.Rare, Value = 8850m, WeaponType = WeaponType.Firearm, FireRate = 3, Ammo = Ammunition.B556mm, HighestDamage = 14, LowestDamage = 7, Cooldown = TimeSpan.FromMinutes(95.156) },
                78 => new Healing() { ID = 78, Name = "Blood Bag", Subname = "Blood", Rarity = Rarity.Epic, Value = 14784m, MaxHealingRate = 90, LowestHealingRate = 70, Cooldown = TimeSpan.FromMinutes(92) },
                79 => new Armor() { ID = 79, Name = "Kevlar Set", Subname = "Kevlar", Rarity = Rarity.Rare, Value = 27562.5m, IsActive = false, ProtectionRate = 75 },
                80 => new Weapon() { ID = 80, Name = "Combat Knife", Subname = "Combat", Rarity = Rarity.Rare, Value = 5510m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 35, LowestDamage = 30, Cooldown = TimeSpan.FromMinutes(73.875), IsPurchaseable = true },
                81 => new Ammo() { ID = 81, Name = "7.62mm", Subname = "762", Rarity = Rarity.Rare, Value = 8921.87m, Type = Ammunition.B762mm },
                82 => new Weapon() { ID = 82, Name = "M1 Garand", Subname = "Garand", Rarity = Rarity.Rare, Value = 15771.87m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B3006, HighestDamage = 50, LowestDamage = 40, Cooldown = TimeSpan.FromMinutes(120.031) },
                83 => new Weapon() { ID = 83, Name = "Kar-98", Subname = "Kar", Rarity = Rarity.Rare, Value = 18068.75m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B762mm, HighestDamage = 55, Cooldown = TimeSpan.FromMinutes(186.593) },
                84 => new Weapon() { ID = 84, Name = "MG-42", Subname = "MG42", Rarity = Rarity.Rare, Value = 17237.5m, WeaponType = WeaponType.Firearm, FireRate = 8, Ammo = Ammunition.B792, HighestDamage = 8, LowestDamage = 4, Cooldown = TimeSpan.FromMinutes(167.5) },
                85 => new Healing() { ID = 85, Name = "Morphine", Subname = "Morph", Rarity = Rarity.Rare, Value = 8024.21m, MaxHealingRate = 65, LowestHealingRate = 50, Cooldown = TimeSpan.FromMinutes(69) },
                86 => new Attachment() { ID = 86, Name = "Dual Mags", Subname = "Dual", Rarity = Rarity.Rare, Value = 6739.10m, IsActive = false, Ability = Addon.ReduceCooldown, Intensity = 25 },
                87 => new Weapon() { ID = 87, Name = "Howa 89", Subname = "Howa", Rarity = Rarity.Rare, Value = 18134.37m, WeaponType = WeaponType.Firearm, FireRate = 4, Ammo = Ammunition.B556mm, HighestDamage = 16, LowestDamage = 8, Cooldown = TimeSpan.FromMinutes(94.25) },
                88 => new Attachment() { ID = 88, Name = "4x Scope", Subname = "4x", Rarity = Rarity.Rare, Value = 9471.99m, IsActive = false, Ability = Addon.HighestDamageIncrease, Intensity = 10 },
                89 => new Weapon() { ID = 89, Name = "Bayonet", Subname = "Bay", Rarity = Rarity.Rare, Value = 4825.62m, WeaponType = WeaponType.Melee, FireRate = 1, Ammo = Ammunition.None, HighestDamage = 30, LowestDamage = 25, Cooldown = TimeSpan.FromMinutes(60.5) },
                90 => new Weapon() { ID = 90, Name = "M1 Carbine", Subname = "Carbine", Rarity = Rarity.Rare, Value = 11506.25m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B30Carbine, HighestDamage = 40, LowestDamage = 30, Cooldown = TimeSpan.FromMinutes(83.468) },
                91 => new Weapon() { ID = 91, Name = "M249", Subname = "249", Rarity = Rarity.Epic, Value = 38800.78m, WeaponType = WeaponType.Firearm, FireRate = 5, Ammo = Ammunition.B556mm, HighestDamage = 20, LowestDamage = 15, Cooldown = TimeSpan.FromMinutes(298.75) },
                92 => new Weapon() { ID = 92, Name = "TAC-50", Subname = "Tac", Rarity = Rarity.Epic, Value = 44830.46m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B50BMG, HighestDamage = 90, Cooldown = TimeSpan.FromMinutes(240.875) },
                93 => new Armor() { ID = 93, Name = "Ballistic Shield", Subname = "Ballistic", Rarity = Rarity.Epic, Value = 83312.5m, IsActive = false, ProtectionRate = 100 },
                94 => new Ammo() { ID = 94, Name = ".50 BMG", Subname = "BMG", Rarity = Rarity.Epic, Value = 12582.19m, Type = Ammunition.B50BMG },
                95 => new Weapon() { ID = 95, Name = "SG 550", Subname = "SG", Rarity = Rarity.Epic, Value = 24389.06m, WeaponType = WeaponType.Firearm, FireRate = 1, Ammo = Ammunition.B56mm, HighestDamage = 70, LowestDamage = 55, Cooldown = TimeSpan.FromMinutes(171.025) },
                96 => new Weapon() { ID = 96, Name = "Boys AT Rifle", Subname = "ATRifle", Rarity = Rarity.Unique, Value = 75634.98m, WeaponType = WeaponType.HeavyFirearm, FireRate = 1, Ammo = Ammunition.BRG55, HighestDamage = 25, Cooldown = TimeSpan.FromMinutes(83.468), Special = Special.ArmorBust },
                97 => new Attachment() { ID = 97, Name = "Extended Clip", Subname = "Extended", Rarity = Rarity.Unique, Value = 50347.87m, Ability = Addon.IncreaseHitRate, Intensity = 1, IsActive = false },
                98 => new Ammo() { ID = 98, Name = "RG.55", Subname = "rg", Rarity = Rarity.Unique, Type = Ammunition.BRG55, Value = 32812.5m },
                99 => new Weapon() { ID = 99, Name = "Gattling Gun", Subname = "Gattling", Rarity = Rarity.Unique, Value = 133185.93m, WeaponType = WeaponType.Firearm, FireRate = 3, Ammo = Ammunition.GattlingDrum, HighestDamage = 40, LowestDamage = 20, Cooldown = TimeSpan.FromMinutes(887.062), Special = Special.SpreadShot },
                100 => new Ammo() { ID = 100, Name = "GattlingDrum", Subname = "Drum", Rarity = Rarity.Unique, Value = 65625m, Type = Ammunition.GattlingDrum },
                101 => new Utility() { ID = 101, Name = "Flare", Rarity = Rarity.Unique, Value = 35743.88m, Uses = 1, Special = Special.SupplyCall },
                102 => new Utility() { ID = 102, Name = "Radar", Rarity = Rarity.Unique, Value = 69347.12m, Uses = 3, Special = Special.Scan },
                103 => new Ammo() { ID = 103, Name = "7.92mm", Subname = "792", Rarity = Rarity.Rare, Value = 7933.59m, Type = Ammunition.B792 },
                104 => new Ammo() { ID = 104, Name = "B56mm", Subname = "56", Rarity = Rarity.Rare, Value = 9640.62m, Type = Ammunition.B56mm },
                105 => new Ammo() { ID = 105, Name = "30.06 Springfield", Subname = "30.06", Rarity = Rarity.Uncommon, Value = 4739.57m, Type = Ammunition.B3006 },
                106 => new Crate() { ID = 106, Name = "Common Crate", Subname = "Common", Rarity = Rarity.Common, Value = 3368.53m, IsPurchaseable = true, IsSellable = false },
                107 => new Crate() { ID = 107, Name = "Uncommon Crate", Subname = "Uncommon", Rarity = Rarity.Uncommon, Value = 6435.59m, IsPurchaseable = true, IsSellable = false },
                108 => new Crate() { ID = 108, Name = "Rare Crate", Subname = "Rare", Rarity = Rarity.Rare, Value = 11937.58m, IsPurchaseable = true, IsSellable = false },
                109 => new Crate() { ID = 109, Name = "Epic Crate", Subname = "Epic", Rarity = Rarity.Epic, Value = 35812.73m, IsSellable = false },
                110 => new Crate() { ID = 110, Name = "Unique Crate", Subname = "Unique", Rarity = Rarity.Unique, Value = 107438.20m, IsSellable = false },
                111 => new Money() { ID = 111, Name = "Money Bag", Subname = "Bag", Rarity = Rarity.Rare, Value = 6250m, HighestAmount = 10000m, LowestAmount = 2500m, IsSellable = false },
                112 => new Money() { ID = 112, Name = "Vault", Subname = "Vlt", Rarity = Rarity.Epic, Value = 37500m, HighestAmount = 50000m, LowestAmount = 25000m, IsSellable = false },
                _ => null,
            };
        }
    }
}
