using System;
using System.Collections.Generic;


namespace GameTime.DotPuzzleModels
{
    public class PuzzleList
    {
        public List<Puzzles> AllPuzzles { get; set; }
        public PuzzleList()
        {
            AllPuzzles = new List<Puzzles>();
            _ = new List<string>();
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- X- X- +- X- X- X- X- X- X- X- X- X- X- X- X-", TimeLimit = TimeSpan.FromSeconds(10), Splitter = 4, DotDifficulty = DotDifficulty.Extreme, Moves = 15 });//Confirmed lowest solution 15
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- O- O- O- X- O- O- O- +- O- O- O- O- O- O- O- O- O- X- O- O- X- O- O- O- O- O- O- O- O- O- O- O- X- O- O- O- O- X- O- O- O- O- X- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 7, DotDifficulty = DotDifficulty.Hard, Moves = 22 });//Lowest solution 22
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- O- O- O- O- X- O- X- O- O- O- X- O- O- +- X- O- O- O- O- O- O- O- O- O- X- O- O- O- X- O- O- O- X- O- X- O- O- O- O- O- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(20), Splitter = 7, DotDifficulty = DotDifficulty.Hard, Moves = 15 });//Confirmed lowest solution 15
            AllPuzzles.Add(new Puzzles() { Puzzle = " +- O- O- O- O- O- O- X- O- O- O- O- X- O- O- O-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 4, DotDifficulty = DotDifficulty.Easy, Moves = 10 });
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- X- O- O- O- O- O- X- O- O- +- O- O- O-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 4, DotDifficulty = DotDifficulty.Easy, Moves = 8 });
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- O- X- O- +- O- O- O- O- O- X- O-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 4, DotDifficulty = DotDifficulty.Easy, Moves = 7 });
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- O- O- X- O- O- O- O- O- O- O- O- X- O- X- O- O- O- O- O- O- O- O- +- O- O- O- O- X- O- O- O-", TimeLimit = TimeSpan.FromSeconds(25), Splitter = 6, DotDifficulty = DotDifficulty.Medium, Moves = 15 });//Lowest solution 13
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- O- O- O- O- O- O- O- O- O- O- O- X- O- O- O- O- O- O- O- O- O- X- +- O- O- O- O- O- O- O- O- O- X- O-", TimeLimit = TimeSpan.FromSeconds(20), Splitter = 6, DotDifficulty = DotDifficulty.Hard, Moves = 15 });//Confirmed Lowest solution 15
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- X- O- X- O- O- O- O- O- O- X- O- X- +- O- O- O- O- O- O- X- O- O-", TimeLimit = TimeSpan.FromSeconds(15), Splitter = 5, DotDifficulty = DotDifficulty.Hard, Moves = 13 });//Confirmed lowest solution 13
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- X- O- O- X- O- O- X- O- O- O- O- O- X- O- O- O- O- O- O- X- O- O- O- O- O- O- O- O- O- O- O- O- O- X- O- X- O- O- O- X- O- O- O- O- O- O- O- X- O- O- O- O- +- X- O- O- O- O- O- X- O- O- O- O- O- X- O- O- X- X- O- O- O- O- O- O- X-", TimeLimit = TimeSpan.FromSeconds(60), Splitter = 9, DotDifficulty = DotDifficulty.Extreme, Moves = 38 });//Confirmed lowest solution 38
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- X- X- X- O- O- O- O- O- X- O- O- O- X- +- O- O- O- X- O- O- O- O- O- O- O- O- X- O- X- X- X- O- O- O- O- X- O- O- O- X- O- O- O- O- O- X- X- X- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(20), Splitter = 9, DotDifficulty = DotDifficulty.Medium, Moves = 21 });//Confirmed lowest solution 19
            AllPuzzles.Add(new Puzzles() { Puzzle = " +- O- O- O- O- O- O- O- O- O- O- X- O- X- O- O- O- O- O- O- O- O- O- X- O- O- O- X- O- O- O- O- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(25), Splitter = 6, DotDifficulty = DotDifficulty.Medium, Moves = 14 });//Lowest solution 12
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- X- O- O- O- O- +- O- O- O- O- O- O- O- X- O- O- X- O- O- O- O- O- O- O- X- O- O- O- O- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(25), Splitter = 6, DotDifficulty = DotDifficulty.Medium, Moves = 13 });//Confirmed lowest solution 11
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- O- O- +- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- X- O- O- O- X-", TimeLimit = TimeSpan.FromSeconds(20), Splitter = 5, DotDifficulty = DotDifficulty.Medium, Moves = 14 });//Confirmed lowest solution 12
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- X- X- O- O- O- O- O- O- O- O- O- O- O- +- O- O- O- O- O- O- X-", TimeLimit = TimeSpan.FromSeconds(20), Splitter = 5, DotDifficulty = DotDifficulty.Medium, Moves = 14 });//Confirmed lowest solution 12
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- X- O- +- O- O- O- O- O- O- O- O- O- O- O- X-", TimeLimit = TimeSpan.FromSeconds(25), Splitter = 4, DotDifficulty = DotDifficulty.Easy, Moves = 9 });//Confirmed lowest solution 7
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- X- O- O- O- O- O- O- O- +- O- O- O- O- O- X-", TimeLimit = TimeSpan.FromSeconds(25), Splitter = 4, DotDifficulty = DotDifficulty.Easy, Moves = 9 });//Confirmed lowest solution 7
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- O- O- O- O- O- O- O- X- O- O- O- O- +- O- O- O- O- X- O- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(15), Splitter = 5, DotDifficulty = DotDifficulty.Hard, Moves = 8 });//Comnfirmed lowest solution 8
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- X- O- O- O- O- O- O- O- X- O- O- O- O- O- O- O- +- O- O- O- O- O- X-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 5, DotDifficulty = DotDifficulty.Easy, Moves = 12 });//Comnfirmed lowest solution 8
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- X- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- +- O- O- O- X- O- O- O-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 5, DotDifficulty = DotDifficulty.Easy, Moves = 8 });//Comnfirmed lowest solution 6
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- O- O- O- O- O- O- O- +- O- O- O- O- O- X-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 4, DotDifficulty = DotDifficulty.Easy, Moves = 13 });//Confirmed lowest solution 9
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- O- O- O- O- O- O- O- X- X- O- O- O- O- O- O- O- O- +- O- O- O- O- X-", TimeLimit = TimeSpan.FromSeconds(20), Splitter = 5, DotDifficulty = DotDifficulty.Medium, Moves = 14 });//Confirmed lowest solution 11
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- +- O- O- X- O- O- O- X- O- O- O- O- O- O- X- O- X- O- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(20), Splitter = 5, DotDifficulty = DotDifficulty.Medium, Moves = 12 });//Confirmed lowest solution 10
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- X- O- O- O- +- O- O- O- O- O- O- X- O- O- X- O- O- O- O- O- X- O- O-", TimeLimit = TimeSpan.FromSeconds(20), Splitter = 5, DotDifficulty = DotDifficulty.Medium, Moves = 12 });//Confirmed lowest solution 10
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- O- X- O- O- O- O- O- O- O- O- O- O- O- O- X- O- O- O- X- O- O- +- O-", TimeLimit = TimeSpan.FromSeconds(20), Splitter = 5, DotDifficulty = DotDifficulty.Medium, Moves = 14 });//Confirmed lowest solution 12
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- X- O- O- O- O- O- O- O- O- X- O- +- O- O- O- X- O- O- X- O-", TimeLimit = TimeSpan.FromSeconds(15), Splitter = 5, DotDifficulty = DotDifficulty.Hard, Moves = 12});//Confirmed loest solution 12
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- X- O- X- O- O- O- O- O- O- +- O- O- O- O- O- O- O- O- O- O- X- O-", TimeLimit = TimeSpan.FromSeconds(15), Splitter = 5, DotDifficulty = DotDifficulty.Hard, Moves = 11 });//Confirmed lowest solution 11
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- X- O- O- O- O- O- O- X- O- X- O- O- O- O- O- +- O- O- X- O- X- O- O- O-", TimeLimit = TimeSpan.FromSeconds(15), Splitter = 5, DotDifficulty = DotDifficulty.Hard, Moves = 13 });//Confirmed lowest solution 13
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- X- O- O- X- O- O- O- O- O- X- O- O- O- O- O- O- X- O- +- O- O-", TimeLimit = TimeSpan.FromSeconds(20), Splitter = 5, DotDifficulty = DotDifficulty.Medium, Moves = 13 });//Confirmed lowest solution 12
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- O- O- X- O- O- O- O- O- O- O- X- O- O- O- O- O- O- O- +- O- O- O- X-", TimeLimit = TimeSpan.FromSeconds(20), Splitter = 5, DotDifficulty = DotDifficulty.Medium, Moves = 16 });//Confirmed lowest solution 16
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- X- O- O- O- X- O- O- O- O- O- O- X- O- O- O- O- O- O- O- X- O- O- +-", TimeLimit = TimeSpan.FromSeconds(20), Splitter = 5, DotDifficulty = DotDifficulty.Medium, Moves = 13 });//confirmed lowest solution 11
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- O- O- O- O- O- +- O- X- O- O- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(25), Splitter = 4, DotDifficulty = DotDifficulty.Easy, Moves = 8 });//Confirmed lowest solution 6
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- O- O- O- O- O- O- O- O- X- +- X-", TimeLimit = TimeSpan.FromSeconds(25), Splitter = 4, DotDifficulty = DotDifficulty.Easy, Moves = 4 });//Confirmed lowest solution 3
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- +- O- O- O- O- X- O- O- O- O- O- X- O- O- O-", TimeLimit = TimeSpan.FromSeconds(25), Splitter = 4, DotDifficulty = DotDifficulty.Easy, Moves = 8 });//Confirmed lowest solution 6
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- O- O- X- O- O- +- O- O- X- O- O-", TimeLimit = TimeSpan.FromSeconds(25), Splitter = 4, DotDifficulty = DotDifficulty.Easy, Moves = 8 });//Confirmed lowest solution 6
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- X- O- O- O- X- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- X- O- X- O- X- O- X- X- O- X- O- X- O- X- O- O- O- +- O- O- O- O- O- O- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(35), Splitter = 7, DotDifficulty = DotDifficulty.Extreme, Moves = 22 });//Confirmed lowest solution 22
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- O- O- O- O- X- O- O- O- X- O- O- O- O- O- O- O- O- O- O- X- O- +- X- O- O- X- O- O- O- O- O- O- O- O- O- O- X- O- O- O- X- O- O- O- O- O- X-", TimeLimit = TimeSpan.FromSeconds(35), Splitter = 7, DotDifficulty = DotDifficulty.Extreme, Moves = 27 });//Confirmed lowest solution 27
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- X- O- O- X- O- O- O- O- O- O- O- O- O- X- O- O- O- +- O- O- X- O- O- O- O- X- O- O- O- X- O- O-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 6, DotDifficulty = DotDifficulty.Extreme, Moves = 18 });//Confirmed lowest solution 18
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- O- O- X- O- X- O- O- O- O- O- O- O- O- O- O- O- X- O- O- O- X- O- +- O- X- O- O- O- X- O- O-", TimeLimit = TimeSpan.FromSeconds(20), Splitter = 6, DotDifficulty = DotDifficulty.Hard, Moves = 14 });//Confirmed lowest solution 14
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- O- O- X- O- O- X- O- O- X- O- O- O- O- X- O- O- O- +- O- O- O- X- O- O- O- O- X- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(20), Splitter = 6, DotDifficulty = DotDifficulty.Hard, Moves = 13 });//Confirmed lowest solution 13
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- X- O- O- O- X- O- O- O- O- O- O- O- O- O- O- O- +- O- X- X- X- O- O- O- O- O- O- O- O- X- O-", TimeLimit = TimeSpan.FromSeconds(20), Splitter = 6, DotDifficulty = DotDifficulty.Hard, Moves = 16 });//Confirmed lowest solution 16
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- X- O- O- O- X- O- O- O- O- O- O- O- O- X- O- O- O- O- +- O- O- O- O- X- O- O- O- O- O- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 6, DotDifficulty = DotDifficulty.Medium, Moves = 18 });//Confirmed lowest solution 12
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- O- O- O- O- O- O- X- O- X- O- O- O- O- O- O- +- O- O- O- O- O- O- X- O- O- O- O- X- O- O- O-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 6, DotDifficulty = DotDifficulty.Medium, Moves = 15 });//Confirmed lowest solution 13
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- O- O- +- O- O- X- O- O- O- O- O- O- O- O- X- O- O- O- X- O- O- O- O- O- O- O- O- O- X- O- O-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 6, DotDifficulty = DotDifficulty.Medium, Moves = 15 });//Confirmed lowest solution 13
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- O- O- O- X- O- O- O- O- O- O- O- O- +- O- X- O- X- O- O- O- O- O- O- O- O- O- O- X- O- O- O-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 6, DotDifficulty = DotDifficulty.Medium, Moves = 15 });//Confirmed lowest solution 13
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- +- O- X- X- O- O- O- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 4, DotDifficulty = DotDifficulty.Easy, Moves = 9 });//Confirmed lowest solution 6
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- X- O- O- X- O- O- O- O- O- O- +- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 4, DotDifficulty = DotDifficulty.Easy, Moves = 9 });//Confirmed lowest solution 6
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- +- X- X- O- O- O- O- O- O- O- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 4, DotDifficulty = DotDifficulty.Easy, Moves = 8 });//Confirmed lowest solution 5
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- O- X- O- O- X- O- +- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 4, DotDifficulty = DotDifficulty.Easy, Moves = 7 });//Confirmed lowest solution 5
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- X- O- O- O- +- O- O- O- O- O- O- X- O- O-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 4, DotDifficulty = DotDifficulty.Easy, Moves = 8 });//Confirmed lowest solution 5
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- X- O- O- O- O- O- +- O- O- O- O- O- O- X-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 4, DotDifficulty = DotDifficulty.Easy, Moves = 11 });//Confirmed lowest solution 8
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- +- X- O- O- O- O- O- O- O- O- X- O- O-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 4, DotDifficulty = DotDifficulty.Easy, Moves = 10 });//Confirmed lowest solution 7
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- +- O- O- O- O- X- O- O- O- X- O-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 4, DotDifficulty = DotDifficulty.Easy, Moves = 6 });//Confirmed lowest solution 3
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- X- O- X- O- O- X- O- O- X- +- X- O- O- X-", TimeLimit = TimeSpan.FromSeconds(20), Splitter = 6, DotDifficulty = DotDifficulty.Hard, Moves = 12 });//Confirmed lowest solution 12
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- X- O- O- O- O- O- O- O- O- O- X- O- O- O- X- O- O- O- +- O- O- X- O- O- O- O- O- O- O- X- O- X- O-", TimeLimit = TimeSpan.FromSeconds(20), Splitter = 6, DotDifficulty = DotDifficulty.Hard, Moves = 19 });//Confirmed lowest solution 19
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- O- O- O- +- O- O- X- O- O- O- O- O- O- X- O- O- O- X- O- O- O- O- O- O- X- O- X- O- O- O- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(20), Splitter = 6, DotDifficulty = DotDifficulty.Hard, Moves = 17 });//Confirmed lowest solution 17
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- O- O- O- O- O- O- O- X- X- O- O- O- O- O- O- +- O- O- O- O- O- X- O-", TimeLimit = TimeSpan.FromSeconds(25), Splitter = 5, DotDifficulty = DotDifficulty.Hard, Moves = 13 });//Confirmed lowest solution 13
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- O- O- O- O- O- O- X- O- O- O- O- O- O- O- O- O- O- X- X- O- O- +- O-", TimeLimit = TimeSpan.FromSeconds(25), Splitter = 5, DotDifficulty = DotDifficulty.Hard, Moves = 13 });//Confirmed lowest solution 13
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- X- O- O- X- O- O- X- O- O- +- O- O- O- O- O- O- X- O- X- O- O-", TimeLimit = TimeSpan.FromSeconds(25), Splitter = 5, DotDifficulty = DotDifficulty.Hard, Moves = 13 });//Confirmed lowest solution 13
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- O- X- O- O- O- O- O- O- O- O- X- O- X- O- O- O- O- O- O- X- O- O- +-", TimeLimit = TimeSpan.FromSeconds(25), Splitter = 5, DotDifficulty = DotDifficulty.Hard, Moves = 14 });//Confirmed lowest solution 14
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- +- O- X- O- O- O- O- O- O- O- X- O- O- X- O- O- O- O- O- O- O- X- O-", TimeLimit = TimeSpan.FromSeconds(25), Splitter = 5, DotDifficulty = DotDifficulty.Hard, Moves = 16 });//Confirmed lowest solution 16
            //AllPuzzles.Add(new Puzzles() { Puzzle = " O- X- O- O- O- O- O- O- O- O- O- O- O- O- +- O- X- O- X- O- O- X- O- O- O- O- O- O- O- X- O- X- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(20), Splitter = 6, DotDifficulty = DotDifficulty.Hard });
            //AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- O- O- X- O- O- X- O- O- O- X- O- O- O- O- O- O- O- O- X- X- O- O- O- +- O- O- O- O- X- O- O-", TimeLimit = TimeSpan.FromSeconds(20), Splitter = 6, DotDifficulty = DotDifficulty.Hard });
            //AllPuzzles.Add(new Puzzles() { Puzzle = " O- X- O- O- O- X- O- O- O- O- O- O- X- O- O- O- O- O- X- O- O- O- +- O- O- X- O- O- O- O- O- O- O- O- O- X-", TimeLimit = TimeSpan.FromSeconds(20), Splitter = 6, DotDifficulty = DotDifficulty.Hard });
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- O- O- O- X- O- +- O-", TimeLimit = TimeSpan.FromSeconds(25), Splitter = 3, DotDifficulty = DotDifficulty.Easy, Moves = 7 });//Confirmed lowest solution 5
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- O- O- O- O- O- O- +-", TimeLimit = TimeSpan.FromSeconds(25), Splitter = 3, DotDifficulty = DotDifficulty.Easy, Moves = 7 });//Confirmed lowest solution 4
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- +- X- O- O-", TimeLimit = TimeSpan.FromSeconds(25), Splitter = 3, DotDifficulty = DotDifficulty.Easy, Moves = 6 });//Confirmed lowest solution 3
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- O- O- O- O- O- O- O- O- O- O- +- O- O- X- O- O- O- O- O- O- O- O- X-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 5, DotDifficulty = DotDifficulty.Medium, Moves = 16 });//Confirmed lowest solution 14
            AllPuzzles.Add(new Puzzles() { Puzzle = " +- O- O- O- O- O- O- O- O- X- X- O- O- O- O- O- X- O- O- O- X- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 5, DotDifficulty = DotDifficulty.Medium, Moves = 13 });//Confirmed lowest solution 11
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- O- O- O- O- O- O- O- O- +- O- O- O- O- X-", TimeLimit = TimeSpan.FromSeconds(15), Splitter = 4, DotDifficulty = DotDifficulty.Medium, Moves = 10 });//Confirmed lowest solution 8
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- X- O- +- O- X- O- O-", TimeLimit = TimeSpan.FromSeconds(10), Splitter = 3, DotDifficulty = DotDifficulty.Medium, Moves = 6 });//Confirmed lowest solution 6
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- O- O- +- O- O- O- X-", TimeLimit = TimeSpan.FromSeconds(10), Splitter = 3, DotDifficulty = DotDifficulty.Medium, Moves = 6 });//Confirmed lowest solution 6
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- O- O- X- O- O- O- O- O- O- O- O- O- O- X- O- O- O- O- O- O- O- O- O- +- O- O- O- O- O- O- X-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 6, DotDifficulty = DotDifficulty.Medium, Moves = 14 });//Confirmed lowest solution 12
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- O- O- O- O- O- O- X- O- +- X- O- O- O- O- O- O- O- O- X- O- X- O- O- O- O- O- O- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 6, DotDifficulty = DotDifficulty.Medium, Moves = 13 });//Confirmed lowest solution 11
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- O- O- X- O- O- O- O- O- O- O- +- X- O- O- X- O- O- O- O- O- O- O- O- O- O- O- O- O- X- O- O-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 6, DotDifficulty = DotDifficulty.Medium, Moves = 13 });//Confirmed lowest solution 11
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- O- O- O- O- O- O- X- O- +- X- O- O- O- O- O- O- O- O- X- O- X- O- O- O- O- O- O- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(20), Splitter = 6, DotDifficulty = DotDifficulty.Medium, Moves = 11 });//Confirmed lowest solution 11
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- O- X- O- O- O- O- O- O- O- O- O- O- +- O- O- X- O- O- X- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 5, DotDifficulty = DotDifficulty.Medium, Moves = 15 });//Confirmed lowest solution 13
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- X- O- O- O- O- O- O- O- O- +- O- O- O- O- O- O- O- O- X- O- X- O- O-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 5, DotDifficulty = DotDifficulty.Medium, Moves = 13 });//Confirmed lowest solution 11
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- O- O- O- O- X- X- O- O- O- O- +- X- O- O- O- O- O- O- X- O-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 5, DotDifficulty = DotDifficulty.Medium, Moves = 12 });//Confirmed lowest solution 10
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- X- O- O- X- O- O- O- O- O- O- O- O- O- O- +- O- O- X- O- O-", TimeLimit = TimeSpan.FromSeconds(35), Splitter = 6, DotDifficulty = DotDifficulty.Medium, Moves = 19 });//Confirmed lowest solution 17
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- X- O- O- O- O- O- O- O- O- O- O- O- O- O- X- O- O- X- O- O- O- O- O- O- O- +- O- O- O- O- O- O- O- O- X-", TimeLimit = TimeSpan.FromSeconds(35), Splitter = 6, DotDifficulty = DotDifficulty.Medium, Moves = 19 });//Confirmed lowest solution 17
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- O- O- O- O- X- O- O- O- O- O- O- O- X- O- O- O- O- +- O- O- O- O- O- O- O- X- O- O- X- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(35), Splitter = 6, DotDifficulty = DotDifficulty.Medium, Moves = 15 });//Confirmed lowest solution 13
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- O- X- O- O- O- O- O- O- X- O- O- +- O- O- O- O- O- O- O- O- O- O- O- O- X- O- O- O- X- O- O- O- O- X-", TimeLimit = TimeSpan.FromSeconds(30), Splitter = 6, DotDifficulty = DotDifficulty.Hard, Moves = 20 });//Confirmed lowest solution 20
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- X- O- O- O- O- X- O- O- O- X- O- O- O- X- O- O- O- O- O- O- O- O- O- +- O- O- X- O- O- O- O- O- O- O- O- X- O- O- O- X- O- O- O- O- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(25), Splitter = 7, DotDifficulty = DotDifficulty.Hard, Moves = 23 });//Confirmed lowest solution 23 
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- O- O- X- O- O- O- O- O- O- O- X- O- O- X- O- O- O- O- O- O- O- O- O- O- O- X- O- O- X- O- O- O- O- O- O- O- O- +- O- O- O- X- O- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(25), Splitter = 7, DotDifficulty = DotDifficulty.Hard, Moves = 22 });//Confirmed lowest solution 22
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- X- O- O- O- O- O- O- O- O- X- O- O- X- O- X- O- O- O- O- O- O- X- O- X- O- O- O- +- O- O- O- O- O- O- O- O- O- X- O- O- O- O- O- O- O- O-", TimeLimit = TimeSpan.FromSeconds(25), Splitter = 7, DotDifficulty = DotDifficulty.Hard, Moves = 16 });//Confirmed lowest solution 16
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- O- O- X- O- O- O- O- X- O- O- O- +- O- O- O- O- O- O- O- O- O- O- X- O- O- O- O- O- O- O- O- X- O- O- O- X- O- O- O- X- O- O- O- O- X- O- O- O-", TimeLimit = TimeSpan.FromSeconds(25), Splitter = 7, DotDifficulty = DotDifficulty.Hard, Moves = 20 });//Lowest solution 20
            AllPuzzles.Add(new Puzzles() { Puzzle = " X- O- X- O- X- O- X- O- O- O- O- O- O- O- O- O- O- O- O- O- O- +- X- O- X- O- X- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- X- O- X- O- X- O-", TimeLimit = TimeSpan.FromSeconds(15), Splitter = 7, DotDifficulty = DotDifficulty.Extreme, Moves = 24 });//Confirmed lowest solution 24
            AllPuzzles.Add(new Puzzles() { Puzzle = " O- X- O- O- O- X- O- O- O- O- O- O- O- O- O- O- X- O- X- O- X- O- +- O- O- O- O- O- O- O- O- O- O- O- O- O- O- O- X- O- O- O- O- O- X- X- O- O- O- O- O- X- O- O- O- O- O- X- O- O- O- X- O- O- X- O- O- O- X- O- O- O- O- O- O- X- O- O- O- X- O-", TimeLimit = TimeSpan.FromSeconds(60), Splitter = 9, DotDifficulty = DotDifficulty.Extreme, Moves = 44 });//Lowest solution 43
        }
        public List<string> ConstructPuzzle(string rawPuzzle)
        {
            List<string> puzzle = new List<string>();
            var splitPuzzle = rawPuzzle.Split("-");
            foreach (var s in splitPuzzle)
            {
                puzzle.Add(s);
            }
            return puzzle;
        }
    }
}